apiVersion: v1
kind: Service
metadata:
  name: sadtalker-service
  namespace: research-experiments  # 指定命名空间
spec:
  type: LoadBalancer  # 或者使用 NodePort 或 ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: sadtalker
